name: PHPUnit and Code Linting

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-suggest --prefer-dist

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run Code Linting
        run: vendor/bin/phpcs --standard=PSR2 -v --extensions=php app/

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/reports/junit.xml
